# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimating_equation_cpp <- function(X, Y, model_type, beta, offset, solve_opts = "fast", maxit = 100L, tol = 1e-8, verbose = FALSE) {
    .Call(`_contICEIPCW_estimating_equation_cpp`, X, Y, model_type, beta, offset, solve_opts, maxit, tol, verbose)
}

